package com.mycompany.datamhs;

public class Dashboard_Mahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_Mahasiswa.class.getName());

    /**
     * Creates new form Dashboard_Mahasiswa
     */
    public Dashboard_Mahasiswa() {
        initComponents();
        loadDataTabel();
    }
    public void loadDataTabel() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("Id Fasilitas");
    model.addColumn("Nama Ruangan");
    model.addColumn("Lokasi");
    model.addColumn("Kapasitas");
    model.addColumn("Status");
    
    try {
        java.sql.Connection conn = koneksi.configDB();
        String sql = "SELECT * FROM fasilitas"; 
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{
                res.getString("idFasilitas"), 
                res.getString("nama"), 
                res.getString("lokasi"),
                res.getString("kapasitas"), 
                res.getString("status") 
            });
        }
        tabelFasilitas.setModel(model);
    } catch (Exception e) {
        System.out.println("Gagal memuat data tabel: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFasilitas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Selamat Datang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DASHBOARD MAHASISWA");

        jButton1.setText("Ajukan Reservasi");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Lihat Ruangan");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Riwayat Reservasi");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Logout");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tabelFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Fasilitas", "Nama Ruangan", "Lokasi ", "Kapasitas", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelFasilitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jButton2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        new Notify().setVisible(true); 
        this.dispose(); 
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int baris = tabelFasilitas.getSelectedRow();
    
    if (baris != -1) {
        String id = tabelFasilitas.getValueAt(baris, 0).toString();
        String nama = tabelFasilitas.getValueAt(baris, 1).toString();
        String lokasi = tabelFasilitas.getValueAt(baris, 2).toString();
        String status = tabelFasilitas.getValueAt(baris, 4).toString();
        
        if (status.equalsIgnoreCase("Dipinjam")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Maaf, ruangan " + nama + " saat ini sedang dipinjam!\nSilakan pilih ruangan lain yang masih tersedia.", 
                "Ruangan Tidak Tersedia", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Jika lolos validasi (Status = 'Tersedia'), form reservasi baru akan terbuka
        new Reservasi(id, nama, lokasi, status).setVisible(true);
        this.dispose(); 
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih ruangan dulu dari tabel!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int barisTerpilih = tabelFasilitas.getSelectedRow(); 
    
    if (barisTerpilih == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu ruangan dari tabel terlebih dahulu!");
        return;
    }
    
    String id = tabelFasilitas.getValueAt(barisTerpilih, 0).toString(); 
    String nama = tabelFasilitas.getValueAt(barisTerpilih, 1).toString();   
    String lokasi = tabelFasilitas.getValueAt(barisTerpilih, 2).toString(); 
    String status = tabelFasilitas.getValueAt(barisTerpilih, 4).toString(); 
    
    Fasilitas formFasilitas = new Fasilitas(id, nama, lokasi, status);

    formFasilitas.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new RiwayatReservasi().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard_Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelFasilitas;
    // End of variables declaration//GEN-END:variables
}
